spring.application.name=resolver
spring.application.description= This is Resolver AI Application

#postgres db connection
spring.datasource.url= jdbc:postgresql://localhost:5432/resolverai
spring.datasource.username=krishnaakumarisahoo
spring.datasource.password=Krishnaa@1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
